### ISSUE TITLE
No "path.posix" in node v0.10.x

### ISSUE THREAD

**Issue by changke** [MarcDiethelm/grunt-less-imports#20]
Hi, after the latest update our build is broken under node.js v0.10.x since you start using "path.posix" which is not available in node v0.10.

The "engines.node" in package.json should be updated to ">= 0.12.0".

**Comment by MarcDiethelm** [comment]
Windows support... making life hard for devs everywhere. Will fix this within 24 hours. But I need to think about the best solution. Removing support for Node 0.10.x is definitely the easiest way out but not something I had in mind when I last updated this tool. Thanks for the bug report!

**Comment by MarcDiethelm** [comment]
I just released version v1.2.2 which fixes your issue, and maintains support for 0.10.x. Please let me know if you encounter any problems.
